[stages.headers]
downloader_max_concurrent_requests = 1000
downloader_min_concurrent_requests = 50
downloader_max_buffered_responses = 1000
downloader_request_limit = 1000
commit_threshold = 15000

[stages.bodies]
downloader_request_limit = 1000
downloader_stream_batch_size = 5000
downloader_max_buffered_blocks_size_bytes = 2147483648
downloader_min_concurrent_requests = 20
downloader_max_concurrent_requests = 750

[stages.sender_recovery]
commit_threshold = 5000000

[stages.execution]
max_blocks = 500000
max_changes = 5000000
max_cumulative_gas = 1500000000000
max_duration = "10m"

[stages.account_hashing]
clean_threshold = 500000
commit_threshold = 100000

[stages.storage_hashing]
clean_threshold = 500000
commit_threshold = 100000

[stages.merkle]
clean_threshold = 50000

[stages.transaction_lookup]
chunk_size = 5000000

[stages.index_account_history]
commit_threshold = 100000

[stages.index_storage_history]
commit_threshold = 100000

[stages.etl]
file_size = 524288000

[peers]
refill_slots_interval = "1s"
trusted_nodes = []
trusted_nodes_only = false
max_backoff_count = 5
ban_duration = "12h"

[peers.connection_info]
max_outbound = 500
max_inbound = 50
max_concurrent_outbound_dials = 20

[peers.reputation_weights]
bad_message = -65536
bad_block = -65536
bad_transactions = -16384
already_seen_transactions = 0
timeout = -4096
bad_protocol = -2147483648
failed_to_connect = -25600
dropped = -25600
bad_announcement = -1024

[peers.backoff_durations]
low = "30s"
medium = "3m"
high = "15m"
max = "1h"

[sessions]
session_command_buffer = 32
session_event_buffer = 260

[sessions.limits]

[sessions.initial_internal_request_timeout]
secs = 20
nanos = 0

[sessions.protocol_breach_request_timeout]
secs = 120
nanos = 0
