{
 "title": "Op-Geth + Op-Node",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Op-Geth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client Info",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geth_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "targets": [
    { "expr": "chain_head_block", "legendFormat": "Head" },
    { "expr": "chain_head_finalized", "legendFormat": "Finalized" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "p2p_peers", "legendFormat": "Peer Count" }
   ]
  },
  {
   "title": "Peer Disconnect Reasons",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2p_dials_error_connection", "legendFormat": "Invalid Connection" },
    { "expr": "p2p_dials_error_id_unexpected", "legendFormat": "UnexpectedIdentity" },
    { "expr": "p2p_dials_error_known", "legendFormat": "AlreadyConnected" },
    { "expr": "p2p_dials_error_rlpx_enc", "legendFormat": "EncHandshakeError" },
    { "expr": "p2p_dials_error_rlpx_proto", "legendFormat": "ProtoHandshakeError" },
    { "expr": "p2p_dials_error_saturated", "legendFormat": "TooManyPeers" },
    { "expr": "p2p_dials_error_self", "legendFormat": "SelfConnection" },
    { "expr": "p2p_dials_error_useless", "legendFormat": "UselessPeer" }
   ]
  },
  {
   "title": "RPC Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 17 },
   "targets": [
    { "expr": "rpc_success", "legendFormat": "Successful" },
    { "expr": "rpc_failure", "legendFormat": "Failed" }
   ]
  },
  { "title": "Op-Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Client Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "op_node_default_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 3, "y": 28 },
   "targets": [
    { "expr": "op_node_default_p2p_peer_count", "legendFormat": "Peers" }
   ]
  },
  {
   "title": "P2P Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 13, "y": 28 },
   "targets": [
    {
     "expr": "op_node_default_p2p_bandwidth_bytes_total{direction=\"in\"}",
     "legendFormat": "In"
    },
    {
     "expr": "op_node_default_p2p_bandwidth_bytes_total{direction=\"out\"}",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "L1 Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "op_node_default_refs_number{layer=\"l1\", type=\"l1_head\"}",
     "legendFormat": "Head"
    },
    {
     "expr": "op_node_default_refs_number{layer=\"l1\", type=\"l1_safe\"}",
     "legendFormat": "Safe"
    },
    {
     "expr": "op_node_default_refs_number{layer=\"l1\", type=\"l1_finalized\"}",
     "legendFormat": "Finalized"
    }
   ]
  },
  {
   "title": "L2 Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 32 },
   "targets": [
    {
     "expr": "op_node_default_refs_number{layer=\"l2\", type=\"l2_unsafe\"}",
     "legendFormat": "Unsafe"
    },
    {
     "expr": "op_node_default_refs_number{layer=\"l2\", type=\"l2_safe\"}",
     "legendFormat": "Head"
    },
    {
     "expr": "op_node_default_refs_number{layer=\"l2\", type=\"l2_finalized\"}",
     "legendFormat": "Head"
    }
   ]
  }
 ]
}